### PR TITLE
Fix plugin and small improvements

### LINKED ISSUE #23: Remove/Remap esc key closing
Are you able to remove/add a option to stop the chatbox from minimising when clicking the esc key? The esc key is used for closing interfaces and doesnt work well with this plugin enabled

### LINKED ISSUE #24: Adjust viewport with chatbox open/closed
Currently when activating the plugin, the viewport expands to fill the new space and has the effect of moving the player character further down, as well as adjusting the FOV (because there's more vertical room). 

I'd like to have a toggle-able option to have the viewport shrink to the original size when the chat box is opened again.

### LINKED ISSUE #28: "fixed mode hide chat" plugin not working
Hi, after the update today the plugin has stopped working. Please could you look into it.

### LINKED ISSUE #29: "Fixed mode hide chat" plugin stopped working after recent update
I logged on today after the new update and the plug in no longer allows me to hide the chat box.

### LINKED ISSUE #30: #Fixed mode hide chat isn't working
Hello, I want to report that after the update the "Fixed Mode hide chat" plugin is not working

### LINKED ISSUE #31: Window being re-sized, but chatbox not being hidden
I'm guessing that [this line](https://github.com/deathbeam/example-plugin/blob/c0c600175fb806dc49f82551b4713f07fbd9ba6d/src/main/java/io/github/deathbeam/plugins/fixedhidechat/FixedHideChatPlugin.java#L106) is returning null? Not sure if something has changed in terms of the identification of the chat box widget in the runelite API?

### PR DESCRIPTION
**Pull request by YvesW**
- Updates build.gradle
- Fixes the recent interface changes (closes #28, closes #29, closes #30, closes #31)
- Removes other deprecated APIs
- Adds the seed vault bank interface
- Adds the option to resize the viewport when closing the chat (closes #24)
- Adds the option to change the escape keybind to a user selected key (closes #23)

In the future I might look at:
- Split PMs randomly moving up and down. Could not replicate at this point, but I might have experienced it in the past.
- The voting interface going offscreen. This is a very common occurence, but there is not vote live so I could not fix this.

If you'd like me to make certain changes, drop commmits or would like to ask me why I opted for certain approaches, feel free to DM me on discord ``@YvesW``, @ me in the RL discord, or just do it here.

### CODE REVIEW

File: src/main/java/io/github/deathbeam/plugins/fixedhidechat/FixedHideChatPlugin.java [hunk 1]
```diff
@@ -153,11 +184,22 @@ public void onMenuOptionClicked(final MenuOptionClicked event)
...
+		widget.setYPositionMode(WidgetPositionMode.ABSOLUTE_TOP);
+		widget.revalidateScroll();
+	}
+
 	private static void changeWidgetHeight(int originalHeight, int newHeight, Widget widget)
 	{
 		if (widget.getHeight() == originalHeight)
 		{
-			widget.setHeight(newHeight);
+			widget.setOriginalHeight(newHeight);
```
Comment (deathbeam) [inline src/main/java/io/github/deathbeam/plugins/fixedhidechat/FixedHideChatPlugin.java:200]: These 3 lines should be probably separate method as well (similar to the changeWidgetXY), othherwise looks good

**Review by deathbeam — CHANGES_REQUESTED** [review]

**Comment by applypresure** [comment]
Hello - The issue of the chat box not being able to close is still present. I assume this is still being worked on. Apologies as I am not super familiar with Github and how all of this works. Thank you for any work you are doing to resolve this.

**Review by deathbeam — APPROVED** [review]

**Comment by YvesW** [comment]
Thanks for reviewing, making the changes and merging, DB! I was quite busy today, so didn't have time to make the requested changes.
